### ISSUE TITLE
The domain validate() method not called in the domain controller save and update methods

### ISSUE THREAD

**Issue by maarten-ritense** [grails/scaffolding#15]
In the scaffolding controller the domain validate() method is not called before the hasErrors() check in the save and update methods of the scaffolded controller. Therefore error messages are not displayed in the create and update views after a form submit.

**Comment by graemerocher** [comment]
https://github.com/grails3-plugins/scaffolding/blob/master/src/main/templates/scaffolding/Controller.groovy#L25

The framework automatically calls `validate()` on the instance prior to passing it to the controller

**Comment by maarten-ritense** [comment]
Than probably the framework is broken because what you mention does not seem to happen. I am using Grails 3.0.10 and tested several times with a domain property for which in the constraints I have a custom validator. The custom validator fails based on the businessrules and returns an error. This is only picked up by the save() method in the update method of the controller. After submitting the form the success message is displayed but the value I changed is not saved. See my class below

```
class Paragraaf extends ContentItem {
    static constraints = {
        parent(nullable: false, validator: {val, obj, errors ->
            if (!(val instanceof Hoofdstuk)) {
                errors.rejectValue('parent', 'parent.not.of.type.hoofdstuk')
            }
        })
    }
}
```

When I copy and paste the method from the scaffolding controller template and add the .validate() it does work as expected and displays the error message instead of the success message.

**Comment by graemerocher** [comment]
Nope there isn't, but that isn't to say there may be a use case that doesn't meet your exceptions. Raise an github issue https://github.com/grails/grails-core/issues

And upload an example that clearly reproduces the problem

**Comment by maarten-ritense** [comment]
Thanks, I will do that.

Cheers
