### ISSUE TITLE
Generated tests fail

### ISSUE THREAD

**Issue by miffels** [grails/scaffolding#4]
Hi,

When I create a fresh project with just a barebones domain class and generated scaffolding, running the tests results in two failures. I am not sure if this is working as intended since there is not an awful lot of thorough documentation for the `3.x` plugins out there yet. Since there are no constraints on newly created domain classes, I would expect the generated tests to pass, though.

Given the folowing setup:

```
~ $ grails -version
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_45

~ $ grails create-app com.myapp.backend.images.image-services
| Application created at ~/image-services

~ $ cd image-services
~/image-services $ grails
[...]

grails> create-domain-class image
| Created grails-app/domain/com/myapp/backend/images/Image.groovy
| Created src/test/groovy/com/myapp/backend/images/ImageSpec.groovy

grails> generate-all com.myapp.backend.images.Image
| Rendered template Controller.groovy to destination grails-app\controllers\com\myapp\backend\images\ImageController.groovy
| Rendered template Spec.groovy to destination src\test\groovy\com\myapp\backend\images\ImageControllerSpec.groovy
| Rendered template edit.gsp to destination grails-app\views\image\edit.gsp
| Rendered template create.gsp to destination grails-app\views\image\create.gsp
| Rendered template index.gsp to destination grails-app\views\image\index.gsp
| Rendered template show.gsp to destination grails-app\views\image\show.gsp
| Scaffolding completed for grails-app\domain\com\myapp\backend\images\Image.groovy

grails> test-app
```

I took the liberty to format the output somewhat more nicely:

```
com.myapp.backend.images.ImageControllerSpec
    Test the save action correctly persists an instance
        Condition not satisfied:

        model.image!= null
        |     |    |
        [:]   null false

    at com.myapp.backend.images.ImageControllerSpec.Test the save action correctly persists an instance(ImageControllerSpec.groovy:44)

    Test the update action performs an update on a valid domain instance
        Condition not satisfied:

        view == 'edit'
        |    |
        null false

    at com.myapp.backend.images.ImageControllerSpec.Test the update action performs an update on a valid domain instance(ImageControllerSpec.groovy:109)

```

Cheers,
Michael

**Comment by fotisp** [comment]
Michael, have you been able to get dynamic scaffolding to work at all in Grails 3.0.1?

**Comment by miffels** [comment]
Hi @fotisp,

I had a look at the sources and to me it looks like there is no dynamic scaffolding anymore, I am afraid.

Quite generally Grails 3 is somewhat awkard since there is no more commercial backing from Pivotal anymore. I am not sure if it is just still very young, or if we won't see more activity at all. Take this plugin for instance, no ACK in four days. Which is a pity, since I just bought the 2nd edition of Grails in Action and was looking forward to some epic Grails productivity.

Cheers,
Michael

**Comment by miffels** [comment]
@fotisp Check out the [related grails dev discussion](https://groups.google.com/forum/#!topic/grails-dev-discuss/6R2YaF96Uts). It looks like for the most part you will only generate the scaffolding once, and it will largely adapt to your changes afterwards.

**Comment by miffels** [comment]
I had a closer look at the generated code and the problem is that _some_ constraints and properties are expected on the domain models. The test expected a request to fail, which of course won't happen if anything is accepted.

**Comment by jeffscottbrown** [comment]
> When I create a fresh project with just a barebones domain class and generated scaffolding, running the tests results in two failures.

The generated test has a TODO in it.  The test will fail until that TODO has been addressed.

**Comment by jeffscottbrown** [comment]
> Quite generally Grails 3 is somewhat awkard since there is no more commercial backing from Pivotal anymore.

FYI...

The behavior described above was the same before we left Pivotal.  It has been that way for quite a long time.

**Comment by jeffscottbrown** [comment]
Every so often someone is perplexed by the fact that the generated tests fail and doesn't look at the test to sort it out.  I wonder if we should change the test so that there is an assertion that fails in the populateValidParams method with a specific error message that will better inform what is required.

**Comment by miffels** [comment]
Hi Jeff,

> The generated test has a TODO in it. The test will fail until that TODO has been addressed.

I had a look at the test cases and it turned out that the tests failed because the domain class I created had no constraints. I am not sure if this needs to be addressed, though.

> Every so often someone is perplexed by the fact that the generated tests fail and doesn't look at the test to sort it out. I wonder if we should change the test so that there is an assertion that fails in the populateValidParams method with a specific error message that will better inform what is required.

I agree, it is obvious when you look at the tests but an assertion would give even more of an hint; something like `assert false, "Provide a populateValidParams implementation for this test suite`

OT:

> > Quite generally Grails 3 is somewhat awkard since there is no more commercial backing from Pivotal anymore.
> > FYI...
> 
> The behavior described above was the same before we left Pivotal. It has been that way for quite a long time.

I did not mean to offend anyone, but was speaking out what I thought back then. I started looking into Grails in April and was somewhat surprised to see how things differed between what was described in `Grails in Action` and Grails 3: Many of the plugins were not available, the migration guide/change notes seemed somewhat incomplete and getting a response from the committers took a while in some cases. I can understand and relate, it is just that I somehow expected the Grails ecosystem to be much more vibrant. Later I read of the discontinued Pivotal support and figured things might be connected, since, for instance there is no Grails 3.x GGTS.

**Comment by miffels** [comment]
@jeffbrown, what do you think about the assertion solution? I could provide the changes in a PR if you think that would be a better solution.

**Comment by graemerocher** [comment]
@miffels Seems reasonable, pull requests welcome.

**Comment by miffels** [comment]
Looking better now, I'd say. There's no mistaking the hint:

```
Failed Tests


Test something


Condition not satisfied:

false

TODO: Provide a populateValidParams() implementation for this generated test suite

    at org.acme.SomeControllerSpec.populateValidParams(SomeControllerSpec.groovy:22)
    at org.acme.SomeControllerSpec.Test something(SomeControllerSpec.groovy:145)

```
