### ISSUE TITLE
Upgrade fields plugin to Grails 4

### ISSUE THREAD

**Issue by ilopmar** [grails/scaffolding#42]
Once the `fields` plugin is upgraded to Grails 4, update it here: https://github.com/grails3-plugins/scaffolding/blob/c0612dbbe4156c549459059de5fbd998c9cf6d5e/build.gradle#L42

**Comment by puneetbehl** [comment]
Fixed with fe5e4583a5e277dc8e6eedae2aa3a0efb6fb7767
