### ISSUE TITLE
install-template install templates to wrong directory

### ISSUE THREAD

**Issue by bavicj** [grails/scaffolding#9]
Hi,
I have vanilla Grails 3.0.2 project. After execution of grails install-template there are 2 templates created, but they are put into directory /src/templates/scaffolding. After I do some changes in those templates and run generate-all, the generated files do not contain my changes. 

I checked sources of the plugin and found out that the plugin reads templates from location /src/main/templates/scaffolding.
After I copied templates to that location and rerun generate-all, generated files contains all the changes I have done in templates.

**Comment by graemerocher** [comment]
Doh, you are right. Thanks!

**Comment by bavicj** [comment]
btw why does the install-template created templates only for create and edit?Shouldn't it also create index and show templates?

**Comment by graemerocher** [comment]
Good question, there are templates here https://github.com/grails3-plugins/scaffolding/tree/master/src/main/templates/scaffolding

**Comment by bavicj** [comment]
Yep, I already copied them to mine project :) But maybe for the future it would be nice that you have directly all the templates accessible for modifying
